/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: x.h
  Source: x.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#ifndef DDSC_X_H
#define DDSC_X_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct OneULong
{
  uint32_t seq;
} OneULong;

extern const dds_topic_descriptor_t OneULong_desc;

#define OneULong__alloc() \
((OneULong*) dds_alloc (sizeof (OneULong)));

#define OneULong_free(d,o) \
dds_sample_free ((d), &OneULong_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_X_H */
