/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: x.c
  Source: x.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "x.h"

static const uint32_t OneULong_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (OneULong, seq),
  DDS_OP_RTS
};

const dds_topic_descriptor_t OneULong_desc =
{
  sizeof (OneULong),
  4u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "OneULong",
  NULL,
  2,
  OneULong_ops,
  ""
};
